spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/products/**

            - id: customer-service
              uri: lb://customer-service
              predicates:
                - Path=/customers/**


server:
  port: 2000

eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/
        register-with-eureka: true
        fetch-registry: true
